spring.application.name=pedidos
spring.datasource.url=jdbc:mysql://localhost:3307/alurafood_pedidos
spring.datasource.username=app
spring.datasource.password=app123

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

eureka.instance.instance-id=${spring.application.name}:${random.int}


server.port=0

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest